service: express-lambda

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:AWS_REGION}

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any